### ISSUE TITLE
Will: Paternity Leave checklist

### ISSUE THREAD

**Issue by willgarrett64** [edge/account#91]
List of outstanding tasks (with notes) for when Will goes on paternity leave.

FIAT tasks
- [x] UI tidy up
- [x] Copywriting
- [x] Payment Methods table
  - already done a table, but need to confirm whether it's in the style wanted.
  - Also need to handle error on update auto top up card button
- [x] Disable auto top up confirmation modal
- [ ] Disable buttons if stripe form not valid (purchase and add payment method)
- [x] Update the Add Funds step of `CreateAccount` to include FIAT
  - we have removed the add funds section completely
- [x] Give option to use saved payment cards to make manual XE purchases (currently only used for auto payments)
- [ ] Style the "Processing Payment" panel in `/billing/payments/purchase`. Almost no styling has been applied just yet
  - this needs doing at some point, but it is a very short lived state, so wasn't a priority. It only shows after a purchase redirect, until the payment has been received.
- [x] Integrate the new purchase status into UI (rather than Stripe status)
- [ ] ~~Add some form of warning if auto top up fails at any point (e.g. next time user logs in they need a warning to say it has failed and been disabled)~~ https://github.com/edge/account-api/issues/76
- [ ] Finalise mobile responsiveness
  - I think this is now done, but want to go through to double check at some point
- [ ] Go through all confirmation modals and move bullet points in line with buttons / put cancel button on left

Non-FIAT tasks
- [ ] (NON-URGENT) Change Server page to have url-controlled tabs (like in Billing) rather than state-controlled tabs
